import Logo from "@/app/_components/Logo";
import Navigation from "@/app/_components/Navigation";

import { Josefin_Sans } from "next/font/google";
const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

// app/layout.tsx or pages/_app.tsx
import "@/app/_style/globals.css";
import Header from "./_components/Header";

export const metadata = {
  //title: "The Wild Station",
  //description: "Generated by Cath",
  title: {
    template: "%s / The Wild Station",
    default: "Welcome / The Wild Station",
  },
  description:
    "Luxurious cabin hotel, located in the heart of the Italian Dolomites, surrounded by beautiful mountains and dark forests",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className}, bg-primary-950 text-primary-100 min-h-screen`}
      >
        <Header />
        <main>{children}</main>
        <footer>Copyright by the Wild Station</footer>
      </body>
    </html>
  );
}
/*export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
*/

// <body className="bg-blue-900 text-gray-50 min-h-screen">
